/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package loginform.swing;

/**
 *
 * @author User
 */
public class circles extends javax.swing.JPanel {

    /**
     * Creates new form circles
     */
    public circles() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        circlePanelShadow1 = new loginform.swing.circlePanelShadow();
        circlePanelShadow2 = new loginform.swing.circlePanelShadow();
        circlePanelShadow3 = new loginform.swing.circlePanelShadow();

        setBackground(new java.awt.Color(0, 0, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        circlePanelShadow1.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout circlePanelShadow1Layout = new javax.swing.GroupLayout(circlePanelShadow1);
        circlePanelShadow1.setLayout(circlePanelShadow1Layout);
        circlePanelShadow1Layout.setHorizontalGroup(
            circlePanelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        circlePanelShadow1Layout.setVerticalGroup(
            circlePanelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        add(circlePanelShadow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 60, 60));

        circlePanelShadow2.setBackground(new java.awt.Color(0, 255, 204));

        javax.swing.GroupLayout circlePanelShadow2Layout = new javax.swing.GroupLayout(circlePanelShadow2);
        circlePanelShadow2.setLayout(circlePanelShadow2Layout);
        circlePanelShadow2Layout.setHorizontalGroup(
            circlePanelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        circlePanelShadow2Layout.setVerticalGroup(
            circlePanelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        add(circlePanelShadow2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 60, 60));

        javax.swing.GroupLayout circlePanelShadow3Layout = new javax.swing.GroupLayout(circlePanelShadow3);
        circlePanelShadow3.setLayout(circlePanelShadow3Layout);
        circlePanelShadow3Layout.setHorizontalGroup(
            circlePanelShadow3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        circlePanelShadow3Layout.setVerticalGroup(
            circlePanelShadow3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        add(circlePanelShadow3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 60, 60));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private loginform.swing.circlePanelShadow circlePanelShadow1;
    private loginform.swing.circlePanelShadow circlePanelShadow2;
    private loginform.swing.circlePanelShadow circlePanelShadow3;
    // End of variables declaration//GEN-END:variables
}
